Repository xiLuiis/BD_Alumnos, pull requests merged in 2022-08, with the labels that each got.

#1 Se modifico el comentario anterior
  src/clases/Pila.java
Labels: help wanted

#2 Volvi a cambiar el mismo comentario
  nbproject/private/private.xml
  src/clases/Pila.java
Labels: help wanted, invalid

#6 No se que es esto
  Olu.pub
  build/classes/clases/Hola que hace.txt
Labels: documentation
